development: &default
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432
  template: template0

test:
  <<: *default
  database: test
